### ISSUE TITLE
target="_blank" for all external links

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/open-source-guidelines#3]
Kramdown supports target=“_blank” for hyperlinks.  We should add this to all outbound links on the site.  

Syntax:
[link](url){:target="_blank"}

**Comment by cmgiven** [comment]
Or should we? My sense is this is going out of vogue as it's kinda user hostile (particularly on mobile).

**Comment by mattbailey0** [comment]
:( But I love users.
