### ISSUE TITLE
2FA - should we require it?

### ISSUE THREAD

**Issue by mattbailey0** [DCgov/open-source-guidelines#6]
The current language suggests that users may want to enable 2FA.  Is this something we should consider requiring?

**Comment by cmgiven** [comment]
I had suggested making it so, at least for anyone who will own a repo (be able to force push) or have access to a private repo.




On November 13, 2015 at 8:00:32 AM EST, Matt Bailey <notifications@github.com> wrote:

The current language suggests that users may want to enable 2FA. Is this something we should consider requiring?

**Comment by cmgiven** [comment]
Recalling the downside Emanuel raised: we'd only be able to verify this after someone was added.




On November 13, 2015 at 8:00:32 AM EST, Matt Bailey <notifications@github.com> wrote:

The current language suggests that users may want to enable 2FA. Is this something we should consider requiring?

**Comment by emanuelfeld** [comment]
Yeah, this would require admins monitoring user settings and sending emails to people who haven't set it up. We could possibly set up a service using a GitHub API to send emails to organization members who don't have it enabled, but there is no way to verify before adding them.
